name: iqb-2023
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - jupyterlab
  - notebook
  - scipy
  - biopython
  - seqlike
  - bokeh
  - nglview
  - seaborn
  - scipy
  - ipywidgets<8.0
  - bioconda::mafft
  - nodejs
